<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblCouponTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblCoupon', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id')->default(0);
            $table->unsignedInteger('valore')->default(0);
            $table->date('periodo_dal')->default('0000-00-00');
            $table->date('periodo_al')->default('0000-00-00');
            $table->integer('durata_min')->default(1);
            $table->integer('adulti_min')->default(1);
            $table->integer('numero')->default(1);
            $table->integer('utilizzati')->default(0);
            $table->string('referente', 100)->default('');
            $table->tinyInteger('attivo')->default(1);
            $table->date('data_chiusura')->default('0000-00-00');
            $table->timestamps();
            $table->index('hotel_id', 'tblcoupon_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblCoupon');
    }
}
