<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblBambiniGratisTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblBambiniGratis', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id')->default(0);
            $table->integer('fino_a_anni')->default(0);
            $table->enum('anni_compiuti', ['compiuti', 'non compiuti'])->default('compiuti');
            $table->integer('fino_a_mesi')->default(0);
            $table->date('valido_dal')->default('0000-00-00');
            $table->date('valido_al')->default('0000-00-00');
            $table->tinyInteger('solo_2_adulti')->default(0);
            $table->text('note');
            $table->tinyInteger('approvata')->default(0);
            $table->dateTime('data_approvazione')->nullable();
            $table->tinyInteger('attivo')->default(1);
            $table->dateTime('created_at')->nullable()->default('1970-01-01 00:00:00');
            $table->dateTime('updated_at')->nullable()->default('1970-01-01 00:00:00');
            $table->index('hotel_id', 'tblbambinigratis_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblBambiniGratis');
    }
}
