<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblInfoPiscinaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblInfoPiscina', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('hotel_id')->nullable();
            $table->integer('sup')->default(0);
            $table->integer('h')->default(0);
            $table->integer('h_min')->default(0);
            $table->integer('h_max')->default(0);
            $table->string('aperto_dal', 255)->default('');
            $table->string('aperto_al', 255)->default('');
            $table->tinyInteger('aperto_annuale')->default(0);
            $table->integer('espo_sole')->default(0);
            $table->tinyInteger('espo_sole_tutto_giorno')->default(0);
            $table->tinyInteger('pos_giardino')->default(0);
            $table->tinyInteger('pos_panoramica')->default(0);
            $table->tinyInteger('pos_spiaggia')->default(0);
            $table->tinyInteger('pos_esterna')->default(0);
            $table->tinyInteger('pos_interna')->default(0);
            $table->tinyInteger('pos_rialzata')->default(0);
            $table->string('suggerimento_posizione_it', 255)->nullable();
            $table->string('suggerimento_posizione_en', 255);
            $table->string('suggerimento_posizione_fr', 255);
            $table->string('suggerimento_posizione_de', 255);
            $table->tinyInteger('suggerimento_visibile')->default(0);
            $table->tinyInteger('coperta')->default(0);
            $table->tinyInteger('riscaldata')->default(0);
            $table->tinyInteger('salata')->default(0);
            $table->tinyInteger('idro')->default(0);
            $table->tinyInteger('idro_cervicale')->default(0);
            $table->tinyInteger('scivoli')->default(0);
            $table->tinyInteger('trampolino')->default(0);
            $table->tinyInteger('aperitivi')->default(0);
            $table->tinyInteger('getto_bolle')->default(0);
            $table->tinyInteger('cascata')->default(0);
            $table->tinyInteger('musica_sub')->default(0);
            $table->tinyInteger('wi_fi')->default(0);
            $table->tinyInteger('pagamento')->default(0);
            $table->tinyInteger('salvataggio')->default(0);
            $table->tinyInteger('nuoto_contro')->default(0);
            $table->integer('lettini_dispo')->default(0);
            $table->text('peculiarita')->nullable();
            $table->string('suggerimento_caratteristica', 255)->default('');
            $table->string('vasca_bimbi_h', 10)->nullable();
            $table->integer('vasca_bimbi_sup')->default(0);
            $table->tinyInteger('vasca_bimbi_riscaldata')->default(0);
            $table->string('suggerimento_vasca_bimbi', 255)->default('');
            $table->integer('vasca_idro_posti_dispo')->default(0);
            $table->tinyInteger('vasca_idro_riscaldata')->default(0);
            $table->tinyInteger('vasca_idro_n_dispo')->default(0);
            $table->tinyInteger('vasca_pagamento')->default(0);
            $table->tinyInteger('vasca_idro_pos_giardino')->default(0);
            $table->tinyInteger('vasca_idro_pos_rialzata')->default(0);
            $table->tinyInteger('vasca_idro_pos_panoramica')->default(0);
            $table->tinyInteger('vasca_idro_pos_spiaggia')->default(0);
            $table->tinyInteger('vasca_idro_pos_interna')->default(0);
            $table->tinyInteger('vasca_idro_pos_esterna')->default(0);
            $table->string('suggerimento_vasca_idro', 255)->default('');
            $table->timestamps();
            $table->index('hotel_id', 'tblinfopiscina_hotel_id_foreign');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblInfoPiscina');
    }
}
