<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblStatsVetrineReadTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblStatsVetrineRead', function (Blueprint $table) {
            $table->date('created_at');
            $table->unsignedInteger('vetrina_id');
            $table->unsignedInteger('hotel_id');
            $table->integer('visits');
            $table->primary(['created_at', 'vetrina_id', 'hotel_id']);
            $table->index('vetrina_id', 'tblstatsvetrineread_vetrina_id_index');
            $table->index('hotel_id', 'tblstatsvetrineread_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblStatsVetrineRead');
    }
}
