<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblMenuTematicoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblMenuTematico', function (Blueprint $table) {
            $table->increments('id');
            $table->enum('lang_id', ['it', 'en', 'fr', 'de']);
            $table->enum('type', ['servizi', 'offerte', 'trattamenti', 'parchi', 'visibilita', 'famiglia'])->nullable();
            $table->integer('macrolocalita_id');
            $table->integer('cms_pagine_id');
            $table->integer('ord');

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblMenuTematico');
    }
}
