<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblListiniMinMaxTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblListiniMinMax', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id')->default(0);
            $table->date('periodo_dal')->nullable();
            $table->date('periodo_al')->nullable();
            $table->decimal('prezzo_sd_min', 6, 2)->default(0.00);
            $table->decimal('prezzo_bb_min', 6, 2)->default(0.00);
            $table->decimal('prezzo_mp_min', 6, 2)->default(0.00);
            $table->decimal('prezzo_pc_min', 6, 2)->default(0.00);
            $table->decimal('prezzo_ai_min', 6, 2)->default(0.00);
            $table->decimal('prezzo_sd_max', 6, 2)->default(0.00);
            $table->decimal('prezzo_bb_max', 6, 2)->default(0.00);
            $table->decimal('prezzo_mp_max', 6, 2)->default(0.00);
            $table->decimal('prezzo_pc_max', 6, 2)->default(0.00);
            $table->decimal('prezzo_ai_max', 6, 2)->default(0.00);
            $table->tinyInteger('attivo')->default(1);
            $table->timestamps();
            $table->index('hotel_id', 'tbllistiniminmax_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblListiniMinMax');
    }
}
