<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblCamereAggiuntiveTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblCamereAggiuntive', function (Blueprint $table) {
            $table->increments('id');
            $table->date('arrivo');
            $table->date('partenza');
            $table->integer('date_flessibili');
            $table->string('trattamento', 255);
            $table->unsignedInteger('adulti');
            $table->unsignedInteger('bambini')->default(0);
            $table->string('eta_bambini', 255)->default('');
            $table->unsignedInteger('mailScheda_id');
            $table->unsignedInteger('mailMultipla_id');
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblCamereAggiuntive');
    }
}
