<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblMailSchedaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblMailScheda', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('hotel_id');
            $table->enum('lang_id', ['it', 'en', 'fr', 'de'])->nullable();
            $table->enum('tipologia', ['doppia', 'mobile', 'normale', 'doppia parziale'])->default('normale');
            $table->string('nome', 255);
            $table->date('arrivo');
            $table->date('partenza');
            $table->tinyInteger('date_flessibili')->default(0);
            $table->integer('adulti');
            $table->integer('bambini');
            $table->integer('camere')->default(0);
            $table->string('eta_bambini', 255);
            $table->string('trattamento', 255);
            $table->string('email', 255);
            $table->string('telefono', 255);
            $table->text('richiesta');
            $table->timestamp('data_invio')->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->string('IP', 255);
            $table->timestamps();
            $table->smallInteger('anno');
            $table->smallInteger('mese');
            $table->string('referer', 255);
            $table->tinyInteger('api_sync')->default(0);
            $table->string('whatsapp', 20)->nullable();
            $table->index(['anno', 'mese', 'hotel_id'], 'tblmailscheda_anno_mese_hotel_id_index');
            $table->index('created_at', 'tblmailscheda_created_at_index');
            $table->index('hotel_id', 'tblmailscheda_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblMailScheda');
    }
}
