<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblUsersAccessLogTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblUsersAccessLog', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id');
            $table->string('ip', 255);
            $table->string('user_agent', 255);
            $table->timestamp('created_at')->default('0000-00-00 00:00:00');
            $table->index('created_at', 'tblusersaccesslog_created_at_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblUsersAccessLog');
    }
}
