<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblHotelTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblHotel', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('commerciale_id')->default(0);
            $table->integer('iperbooking_id')->default(0);
            $table->string('nome', 100)->default('');
            $table->string('indirizzo', 100)->default('');
            $table->integer('localita_id')->default(0);
            $table->unsignedInteger('gruppo_id')->default(0);
            $table->string('cap', 5)->default('');
            $table->string('telefono', 100)->default('');
            $table->string('fax', 100)->nullable()->default('');
            $table->string('cell', 100)->default('');
            $table->string('whatsapp', 100)->nullable()->default('');
            $table->text('notewa_it')->nullable();
            $table->text('notewa_en')->nullable();
            $table->text('notewa_fr')->nullable();
            $table->text('notewa_de')->nullable();
            $table->string('skype', 100)->default('');
            $table->string('email', 150)->nullable()->default('');
            $table->string('email_risponditori', 255);
            $table->string('email_secondaria', 255)->nullable();
            $table->string('link', 150)->nullable()->default('');
            $table->tinyInteger('nascondi_url');
            $table->string('testo_link', 100)->default('');
            $table->string('listing_img', 100)->default('');
            $table->tinyInteger('attivo')->default(0);
            $table->tinyInteger('chiuso_temp')->nullable()->default(0);
            $table->string('note', 255)->default('');
            $table->integer('categoria_id')->default(0);
            $table->integer('tipologia_id')->default(0);
            $table->tinyInteger('annuale')->default(0);
            $table->integer('numero_click')->default(0);
            $table->string('mappa_latitudine', 10)->default('');
            $table->string('mappa_longitudine', 10)->default('');
            $table->decimal('prezzo_min', 6, 2)->default(0.00);
            $table->decimal('prezzo_max', 6, 2)->default(0.00);
            $table->decimal('rating_ia', 2, 1)->default(4.0);
            $table->tinyInteger('mail_multipla')->default(1);
            $table->tinyInteger('mail_upselling')->default(1);
            $table->decimal('distanza_centro', 10, 1)->default(0.0);
            $table->decimal('distanza_staz', 10, 1)->default(0.0);
            $table->decimal('distanza_spiaggia', 10, 1)->default(0.0);
            $table->decimal('distanza_fiera', 10, 2)->default(0.00);
            $table->integer('aperto_eventi_e_fiere')->default(0);
            $table->tinyInteger('aperto_pasqua')->default(0);
            $table->tinyInteger('aperto_capodanno')->default(0);
            $table->tinyInteger('aperto_25_aprile')->default(0);
            $table->tinyInteger('aperto_1_maggio')->default(0);
            $table->tinyInteger('aperto_altro_check')->default(0);
            $table->string('aperto_altro_it', 100)->nullable();
            $table->string('aperto_altro_en', 255);
            $table->string('aperto_altro_fr', 255);
            $table->string('aperto_altro_de', 255);
            $table->date('aperto_dal')->default('0000-00-00');
            $table->date('aperto_al')->default('0000-00-00');
            $table->tinyInteger('wifi_gratis')->default(0);
            $table->tinyInteger('reception_24h')->default(0);
            $table->string('reception1_da', 50)->default('');
            $table->string('reception1_a', 50)->default('');
            $table->string('reception2_da', 50)->default('');
            $table->string('reception2_a', 50)->default('');
            $table->text('checkin_it')->nullable();
            $table->text('checkout_it')->nullable();
            $table->text('checkin_en');
            $table->text('checkout_en');
            $table->text('checkin_fr');
            $table->text('checkout_fr');
            $table->text('checkin_de');
            $table->text('checkout_de');
            $table->string('colazione_da', 50)->default('');
            $table->string('colazione_a', 50)->default('');
            $table->string('pranzo_da', 50)->default('');
            $table->string('pranzo_a', 50)->default('');
            $table->string('cena_da', 50)->default('');
            $table->string('cena_a', 50)->default('');
            $table->tinyInteger('trattamento_ai')->default(0);
            $table->tinyInteger('trattamento_pc')->default(0);
            $table->tinyInteger('trattamento_mp')->default(0);
            $table->tinyInteger('trattamento_mp_spiaggia')->nullable()->default(0);
            $table->tinyInteger('trattamento_bb')->default(0);
            $table->tinyInteger('trattamento_bb_spiaggia')->nullable()->default(0);
            $table->tinyInteger('trattamento_sd')->default(0);
            $table->tinyInteger('trattamento_sd_spiaggia')->nullable()->default(0);
            $table->text('note_ai_it')->nullable();
            $table->text('note_ai_en')->nullable();
            $table->text('note_ai_fr')->nullable();
            $table->text('note_ai_de')->nullable();
            $table->text('note_pc_it')->nullable();
            $table->text('note_pc_en')->nullable();
            $table->text('note_pc_fr')->nullable();
            $table->text('note_pc_de')->nullable();
            $table->text('note_mp_it')->nullable();
            $table->text('note_mp_en')->nullable();
            $table->text('note_mp_fr')->nullable();
            $table->text('note_mp_de')->nullable();
            $table->text('note_mp_spiaggia_it')->nullable();
            $table->text('note_mp_spiaggia_en')->nullable();
            $table->text('note_mp_spiaggia_fr')->nullable();
            $table->text('note_mp_spiaggia_de')->nullable();
            $table->text('note_bb_it')->nullable();
            $table->text('note_bb_en')->nullable();
            $table->text('note_bb_fr')->nullable();
            $table->text('note_bb_de')->nullable();
            $table->text('note_bb_spiaggia_it')->nullable();
            $table->text('note_bb_spiaggia_en')->nullable();
            $table->text('note_bb_spiaggia_fr')->nullable();
            $table->text('note_bb_spiaggia_de')->nullable();
            $table->text('note_sd_it')->nullable();
            $table->text('note_sd_en')->nullable();
            $table->text('note_sd_fr')->nullable();
            $table->text('note_sd_de')->nullable();
            $table->text('note_sd_spiaggia_it')->nullable();
            $table->text('note_sd_spiaggia_en')->nullable();
            $table->text('note_sd_spiaggia_fr')->nullable();
            $table->text('note_sd_spiaggia_de')->nullable();
            $table->tinyInteger('trattamenti_moderati')->nullable();
            $table->dateTime('data_moderazione')->nullable();
            $table->tinyInteger('caparra')->default(-1);
            $table->tinyInteger('caparra_no');
            $table->tinyInteger('caparra_si');
            $table->tinyInteger('caparra_altro_check')->default(0);
            $table->string('caparra_altro_it', 100)->nullable();
            $table->string('caparra_altro_en', 255);
            $table->string('caparra_altro_fr', 255);
            $table->string('caparra_altro_de', 255);
            $table->integer('n_camere')->default(0);
            $table->integer('n_posti_letto')->default(0);
            $table->integer('n_appartamenti')->default(0);
            $table->integer('n_suite')->default(0);
            $table->string('telefoni_mobile_call', 255)->default('');
            $table->tinyInteger('contanti')->default(0);
            $table->string('note_contanti_it', 255)->nullable();
            $table->string('note_contanti_en', 255);
            $table->string('note_contanti_fr', 255);
            $table->string('note_contanti_de', 255);
            $table->tinyInteger('assegno')->default(0);
            $table->string('note_assegno_it', 255)->nullable();
            $table->string('note_assegno_en', 255);
            $table->string('note_assegno_fr', 255);
            $table->string('note_assegno_de', 255);
            $table->tinyInteger('carta_credito')->default(0);
            $table->string('note_carta_credito_it', 255)->nullable();
            $table->string('note_carta_credito_en', 255);
            $table->string('note_carta_credito_fr', 255);
            $table->string('note_carta_credito_de', 255);
            $table->tinyInteger('bonifico')->default(0);
            $table->string('note_bonifico_it', 255)->nullable();
            $table->string('note_bonifico_en', 255);
            $table->string('note_bonifico_fr', 255);
            $table->string('note_bonifico_de', 255);
            $table->tinyInteger('paypal')->default(0);
            $table->tinyInteger('bancomat')->default(0);
            $table->string('note_bancomat_it', 255)->nullable()->default('');
            $table->string('note_bancomat_en', 255)->nullable()->default('');
            $table->string('note_bancomat_fr', 255)->nullable()->default('');
            $table->string('note_bancomat_de', 255)->nullable()->default('');
            $table->string('note_paypal_it', 255)->nullable();
            $table->string('note_paypal_en', 255);
            $table->string('note_paypal_fr', 255);
            $table->string('note_paypal_de', 255);
            $table->tinyInteger('inglese')->default(0);
            $table->tinyInteger('francese')->default(0);
            $table->tinyInteger('tedesco')->default(0);
            $table->tinyInteger('spagnolo')->default(0);
            $table->tinyInteger('russo')->default(0);
            $table->string('altra_lingua_it', 255)->nullable();
            $table->string('altra_lingua_en', 255);
            $table->string('altra_lingua_fr', 255);
            $table->string('altra_lingua_de', 255);
            $table->tinyInteger('green_booking')->default(0);
            $table->tinyInteger('eco_sostenibile')->default(0);
            $table->tinyInteger('chiedi_camere')->default(0);
            $table->tinyInteger('preventivo_whatsapp')->default(0);
            $table->integer('accettazioneCaption_id')->default(0);
            $table->text('tmp_punti_di_forza_it');
            $table->text('tmp_punti_di_forza_slug_it');
            $table->text('tmp_punti_di_forza_en');
            $table->text('tmp_punti_di_forza_slug_en');
            $table->text('tmp_punti_di_forza_fr');
            $table->text('tmp_punti_di_forza_slug_fr');
            $table->text('tmp_punti_di_forza_de');
            $table->text('tmp_punti_di_forza_slug_de');
            $table->tinyInteger('organizzazione_comunioni')->default(0);
            $table->tinyInteger('organizzazione_cresime')->default(0);
            $table->tinyInteger('organizzazione_matrimoni')->default(0);
            $table->text('note_organizzazione_matrimoni');
            $table->timestamps();
            $table->tinyInteger('certificazione_aci')->default(0);
            $table->integer('count_preferiti')->default(0);
            $table->integer('bonus_vacanze_2020')->default(0);
            $table->index('localita_id', 'tblhotel_localita_id_index');
            $table->index('categoria_id', 'tblhotel_categoria_id_index');
            $table->index('tipologia_id', 'tblhotel_tipologia_id_index');
            $table->index('attivo', 'tblhotel_attivo_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblHotel');
    }
}
