<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblDatiAggiuntiviEmailsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblDatiAggiuntiviEmails', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('id_mail_diretta');
            $table->integer('id_mail_multipla');
            $table->text('id_result');
            $table->text('duplicate_id_result');
            $table->text('ids_send_mail');
            $table->text('risultato_confronto');
            $table->string('codice_cookie', 100);
            $table->text('old_cookie');
            $table->text('new_cookie');
            $table->string('error_code', 255);
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblDatiAggiuntiviEmails');
    }
}
