<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblGestioneMultipleTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblGestioneMultiple', function (Blueprint $table) {
            $table->integer('id')->unsigned();
            $table->integer('hotel_id');
            $table->integer('contact')->default(1);
            $table->primary(['id', 'hotel_id']);
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
       	DB::statement('ALTER TABLE tblGestioneMultiple MODIFY id INTEGER NOT NULL AUTO_INCREMENT');
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblGestioneMultiple');
    }
}
