<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblSpotHomepageLangTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblSpotHomepageLang', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('id_spot');
            $table->enum('lang', ['it', 'en', 'fr', 'de']);
            $table->string('titolo', 255);
            $table->longText('testo');
            $table->string('link', 500);
            $table->string('immagine', 255);
            $table->string('bottone', 100);
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblSpotHomepageLang');
    }
}
