<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblSpotHomepageTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblSpotHomepage', function (Blueprint $table) {
            $table->increments('id');
            $table->string('titolo', 255);
            $table->string('giorno_inizio', 2);
            $table->string('mese_inizio', 2);
            $table->string('anno_inizio', 4);
            $table->integer('visto');
            $table->integer('layout');
            $table->date('da');
            $table->date('a');
            $table->timestamps();
            $table->integer('validita')->nullable();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblSpotHomepage');
    }
}
