<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblParoleChiaveEspanseTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblParoleChiaveEspanse', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('parolaChiave_id');
            $table->string('chiave', 255);
            $table->timestamps();
            $table->index('parolaChiave_id', 'tblparolechiaveespanse_parolachiave_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblParoleChiaveEspanse');
    }
}
