<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblTassaSoggiornoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblTassaSoggiorno', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id');
            $table->tinyInteger('attiva');
            $table->tinyInteger('applicata')->default(0);
            $table->tinyInteger('inclusa');
            $table->decimal('valore', 6, 2);
            $table->tinyInteger('bambini_esenti');
            $table->integer('eta_bambini_esenti');
            $table->nullableTimestamps();
            $table->tinyInteger('validita_data');
            $table->date('data_iniziale');
            $table->date('data_finale');
            $table->integer('max_giorni');

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblTassaSoggiorno');
    }
}
