<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblServiziTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblServizi', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('gruppo_id')->default(0);
            $table->integer('categoria_id');
            $table->string('icona', 255)->default('');
            $table->tinyInteger('attivo')->default(1);
            $table->integer('admin_position')->default(0);
            $table->tinyInteger('ricerca_mappa')->default(0);
            $table->string('nome_it', 255)->default('');
            $table->string('nome_en', 255)->default('');
            $table->string('nome_fr', 255)->default('');
            $table->string('nome_de', 255)->default('');
            $table->integer('order_ricerca_mappa')->default(0);
            $table->timestamps();
            $table->index('gruppo_id', 'tblservizi_gruppo_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblServizi');
    }
}
