<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblCmsPagineTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblCmsPagine', function (Blueprint $table) {
            $table->increments('id');
            $table->enum('lang_id', ['it', 'en', 'fr', 'de']);
            $table->tinyInteger('attiva');
            $table->string('uri', 255);
            $table->string('alternate_uri', 10);
            $table->string('template', 255);
            $table->tinyInteger('menu_riviera_romagnola')->default(0);
            $table->tinyInteger('vetrine_top_enabled')->default(0);
            $table->string('seo_title', 255);
            $table->string('seo_description', 255);
            $table->string('immagine', 255);
            $table->string('h1', 255);
            $table->string('h2', 255);
            $table->text('descrizione_1');
            $table->text('descrizione_2');
            $table->integer('menu_macrolocalita_id');
            $table->integer('menu_localita_id');
            $table->integer('vetrina_id');
            $table->integer('evidenza_vetrina_id');
            $table->integer('banner_vetrina_id');
            $table->integer('macrolocalita_count');
            $table->string('ancora', 255);
            $table->date('menu_dal');
            $table->date('menu_al');
            $table->tinyInteger('menu_auto_annuale')->default(0);
            $table->tinyInteger('listing_attivo');
            $table->integer('listing_count');
            $table->integer('listing_macrolocalita_id');
            $table->integer('listing_localita_id');
            $table->string('indirizzo_stradario', 255)->default('');
            $table->integer('localita_id_stradario')->nullable();
            $table->integer('macrolocalita_id_stradario')->nullable();
            $table->string('punto_di_forza', 255)->default('');
            $table->integer('listing_puntoForzaChiave_id')->default(0);
            $table->integer('listing_parolaChiave_id');
            $table->enum('listing_offerta', ['', 'offerta', 'lastminute'])->default('');
            $table->enum('listing_offerta_prenota_prima', ['', 'offerta_prenota_prima'])->default('');
            $table->integer('listing_gruppo_servizi_id');
            $table->string('listing_categorie', 255);
            $table->string('listing_tipologie', 255);
            $table->string('listing_trattamento', 255);
            $table->tinyInteger('listing_coupon');
            $table->tinyInteger('listing_bambini_gratis');
            $table->tinyInteger('listing_whatsapp');
            $table->tinyInteger('listing_green_booking')->default(0);
            $table->tinyInteger('listing_eco_sostenibile')->default(0);
            $table->tinyInteger('listing_annuali');
            $table->integer('n_offerte')->default(0);
            $table->string('prezzo_minimo', 255)->default('0');
            $table->string('prezzo_massimo', 255)->default('0');
            $table->tinyInteger('listing_preferiti')->default(0);
            $table->string('tipo_evidenza_crm', 255);
            $table->timestamps();
            $table->tinyInteger('menu_evidenza')->default(0);
            $table->tinyInteger('listing_bonus_vacanze_2020');
            $table->unique('uri', 'tblcmspagine_uri_unique');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblCmsPagine');
    }
}
