<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblHotelServiziTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblHotelServizi', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id')->default(0);
            $table->integer('servizio_id')->default(0);
            $table->text('note');
            $table->text('note_en');
            $table->text('note_fr');
            $table->text('note_de');
            $table->integer('position')->default(0);
            $table->timestamps();
            $table->index('hotel_id', 'tblhotelservizi_hotel_id_index');
            $table->index('servizio_id', 'tblhotelservizi_servizio_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblHotelServizi');
    }
}
