<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblVetrineBambiniGratisTopTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblVetrineBambiniGratisTop', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('hotel_id');
            $table->string('mese', 255);
            $table->integer('fino_a_anni');
            $table->enum('anni_compiuti', ['compiuti', 'non compiuti'])->default('compiuti');
            $table->integer('fino_a_mesi');
            $table->date('valido_dal');
            $table->date('valido_al');
            $table->tinyInteger('attivo')->default(1);
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblVetrineBambiniGratisTop');
    }
}
