<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblOffertePrenotaPrimaLangTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblOffertePrenotaPrimaLang', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('master_id');
            $table->enum('lang_id', ['it', 'en', 'fr', 'de']);
            $table->string('titolo', 255);
            $table->text('testo');
            $table->tinyInteger('approvata')->default(0);
            $table->dateTime('data_approvazione')->nullable();
            $table->timestamps();
            $table->index(['master_id', 'lang_id'], 'master_id');
            $table->index('master_id', 'tblofferteprenotaprimalang_master_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblOffertePrenotaPrimaLang');
    }
}
