<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblListiniCustomLangTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblListiniCustomLang', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('master_id');
            $table->enum('lang_id', ['it', 'en', 'fr', 'de']);
            $table->string('titolo', 255);
            $table->string('sottotitolo', 255);
            $table->text('descrizione');
            $table->text('tabella');
            $table->timestamps();
            $table->index('master_id', 'tbllistinicustomlang_master_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblListiniCustomLang');
    }
}
