<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblDescrizioneHotelTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblDescrizioneHotel', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id')->default(0);
            $table->string('video_url', 150)->nullable()->default('');
            $table->timestamps();
            $table->string('revision_name', 500)->default('Default');
            $table->tinyInteger('online')->default(0);
            $table->index('hotel_id', 'tbldescrizionehotel_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblDescrizioneHotel');
    }
}
