<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblListiniCustomTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblListiniCustom', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id');
            $table->tinyInteger('attivo');
            $table->tinyInteger('intestazione');
            $table->integer('position');
            $table->timestamps();
            $table->index('hotel_id', 'tbllistinicustom_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblListiniCustom');
    }
}
