<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblStatsHotelCallReadTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblStatsHotelCallRead', function (Blueprint $table) {
            $table->smallInteger('anno');
            $table->tinyInteger('mese');
            $table->tinyInteger('giorno');
            $table->unsignedInteger('hotel_id');
            $table->integer('calls');
            $table->primary(['anno', 'mese', 'giorno', 'hotel_id']);
            $table->index('hotel_id', 'tblstatshotelcallread_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblStatsHotelCallRead');
    }
}
