<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblSpotPagineTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblSpotPagine', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('id_pagina');
            $table->integer('spot_attivo')->default(0);
            $table->integer('spot_attivo_footer')->default(0);
            $table->string('spot_h1', 255);
            $table->integer('spot_ordine');
            $table->integer('spot_ordine_footer');
            $table->string('spot_h2', 255);
            $table->string('spot_colore', 255);
            $table->string('spot_video', 255);
            $table->text('spot_descrizione');
            $table->text('spot_immagine');
            $table->date('spot_visibile_dal');
            $table->date('spot_visibile_al');
            $table->tinyInteger('spot_visibile_ricorsivo');
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblSpotPagine');
    }
}
