<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblOfferteIpernetTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblOfferteIpernet', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('id_iper');
            $table->tinyInteger('processata')->default(0);
            $table->integer('minchildren')->nullable();
            $table->integer('minadults')->nullable();
            $table->integer('maxchildren')->nullable();
            $table->integer('maxadults')->nullable();
            $table->integer('minlos')->nullable();
            $table->integer('maxlos')->nullable();
            $table->string('type', 50)->default('');
            $table->tinyInteger('attiva')->default(0);
            $table->date('valida_dal')->nullable();
            $table->date('valida_al')->nullable();
            $table->string('boardtypes', 50)->default('');
            $table->string('titolo_IT', 255)->default('');
            $table->text('descrizione_IT')->nullable();
            $table->string('titolo_EN', 255)->default('');
            $table->text('descrizione_EN')->nullable();
            $table->string('titolo_FR', 255)->default('');
            $table->text('descrizione_FR')->nullable();
            $table->string('titolo_DE', 255)->default('');
            $table->text('descrizione_DE')->nullable();
            $table->text('configurazione')->nullable();
            $table->timestamps();
            $table->unique('id_iper', 'tblofferteipernet_id_iper_unique');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblOfferteIpernet');
    }
}
