<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEvidenzeForExportToIa2019Table extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('evidenze_for_export_to_ia_2019', function (Blueprint $table) {
            $table->integer('id_mese');
            $table->integer('id_hotel')->default(0);
            $table->integer('id_tipo_evidenza');
            $table->integer('costo')->default(0);
            $table->integer('id_macro');
            $table->string('nome', 150)->default('');
            $table->enum('macrotipologia', ['OFFERTE', 'SERVIZI', 'TRATTAMENTI', 'PARCHI DIVERTIMENTO'])->default('OFFERTE');

            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('evidenze_for_export_to_ia_2019');
    }
}
