<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblMailMultipleTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblMailMultiple', function (Blueprint $table) {
            $table->increments('id');
            $table->enum('lang_id', ['it', 'en', 'fr', 'de'])->nullable();
            $table->enum('tipologia', ['normale', 'wishlist', 'mobile', 'doppia', 'doppia parziale'])->nullable()->default('normale');
            $table->string('nome', 255);
            $table->date('arrivo');
            $table->date('partenza');
            $table->integer('date_flessibili');
            $table->string('trattamento', 255);
            $table->integer('adulti');
            $table->integer('bambini');
            $table->integer('camere')->default(0);
            $table->string('eta_bambini', 255);
            $table->string('email', 255);
            $table->text('richiesta');
            $table->timestamp('data_invio')->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->string('IP', 255);
            $table->string('referer', 255);
            $table->tinyInteger('api_sync')->default(0);
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblMailMultiple');
    }
}
