<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblStatsHotelArchiveTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblStatsHotelArchive', function (Blueprint $table) {
            $table->enum('lang_id', ['it', 'en', 'fr', 'de']);
            $table->unsignedInteger('hotel_id');
            $table->string('referer', 255)->nullable();
            $table->string('useragent', 255);
            $table->timestamp('created_at')->default('0000-00-00 00:00:00');

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblStatsHotelArchive');
    }
}
