<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblSlotVetrineTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblSlotVetrine', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('vetrina_id')->default(0);
            $table->integer('hotel_id')->default(0);
            $table->string('hotel_nome', 255);
            $table->integer('hotel_categoria_id');
            $table->integer('hotel_prezzo_min');
            $table->integer('hotel_prezzo_max');
            $table->string('tooltip', 255)->default('');
            $table->integer('pagina');
            $table->integer('posizione');
            $table->unsignedInteger('pointer')->default(0);
            $table->string('immagine', 255)->default('');
            $table->string('link', 255)->default('');
            $table->tinyInteger('attiva')->default(1);
            $table->date('data_scadenza')->default('0000-00-00');
            $table->string('titolo', 255)->default('');
            $table->decimal('prezzo', 6, 2)->default(0.00);
            $table->timestamps();
            $table->index('hotel_id', 'tblslotvetrine_hotel_id_index');
            $table->index('vetrina_id', 'tblslotvetrine_vetrina_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblSlotVetrine');
    }
}
