<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblLocalitaVetrineTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblLocalitaVetrine', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('localita_id');
            $table->unsignedInteger('vetrina_id');
            $table->index('localita_id', 'tbllocalitavetrine_localita_id_index');
            $table->index('vetrina_id', 'tbllocalitavetrine_vetrina_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblLocalitaVetrine');
    }
}
