<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblOfferteTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblOfferte', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('old_id')->default(0);
            $table->enum('tipologia', ['offerta', 'lastminute'])->default('offerta');
            $table->integer('durata_giorni')->default(0);
            $table->date('valido_dal')->default('0000-00-00');
            $table->date('valido_al')->default('0000-00-00');
            $table->integer('hotel_id')->default(0);
            $table->decimal('prezzo_totale', 6, 2)->default(0.00);
            $table->tinyInteger('attivo')->default(0);
            $table->text('note')->nullable();
            $table->tinyInteger('prezzo_a_partire_da')->default(0);
            $table->tinyInteger('label_costo_a_persona')->default(1);
            $table->decimal('prezzo_a_persona', 6, 2)->default(0.00);
            $table->integer('per_persone')->default(1);
            $table->integer('per_giorni')->default(1);
            $table->string('formula', 4)->default('1');
            $table->timestamps();
            $table->index('old_id', 'old_id');
            $table->index('hotel_id', 'tblofferte_hotel_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblOfferte');
    }
}
