<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblCouponAttivazioniTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblCouponAttivazioni', function (Blueprint $table) {
            $table->increments('id');
            $table->string('email', 150)->default('');
            $table->tinyInteger('attivato')->default(0);
            $table->integer('coupon_id')->default(0);
            $table->dateTime('data_attivazione')->default('0000-00-00 00:00:00');
            $table->string('IP', 15)->default('');
            $table->string('user_agent', 150)->default('');
            $table->string('uniqueID', 40)->default('');
            $table->timestamps();
            $table->index('coupon_id', 'tblcouponattivazioni_coupon_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblCouponAttivazioni');
    }
}
