<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblVetrineOfferteTopTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblVetrineOfferteTop', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('hotel_id');
            $table->string('mese', 255);
            $table->tinyInteger('prezzo_a_partire_da')->default(0);
            $table->tinyInteger('label_costo_a_persona')->default(1);
            $table->integer('prezzo_a_persona')->default(0);
            $table->integer('per_persone')->default(0);
            $table->integer('per_giorni')->default(0);
            $table->string('formula', 4)->default('');
            $table->date('valido_dal');
            $table->date('valido_al');
            $table->date('prenota_entro');
            $table->integer('perc_sconto')->default(0);
            $table->enum('tipo', ['offerta', 'lastminute', 'prenotaprima'])->default('offerta');
            $table->tinyInteger('attivo')->default(1);
            $table->tinyInteger('nascondi_in_scheda')->default(0);
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblVetrineOfferteTop');
    }
}
