<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblVetrineTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblVetrine', function (Blueprint $table) {
            $table->increments('id');
            $table->string('nome', 255)->default('');
            $table->text('descrizione');
            $table->integer('pagine');
            $table->integer('pagina_corrente');
            $table->tinyInteger('attiva')->default(1);
            $table->integer('tipoVetrina_id')->default(0);
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblVetrine');
    }
}
