<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblMacrolocalitaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblMacrolocalita', function (Blueprint $table) {
            $table->increments('id');
            $table->string('nome', 255);
            $table->decimal('latitudine', 10, 6);
            $table->decimal('longitudine', 10, 6);
            $table->integer('zoom');
            $table->string('linked_file', 100);
            $table->string('image', 100);
            $table->timestamps();

            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblMacrolocalita');
    }
}
