<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblInfoBenessereTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblInfoBenessere', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('hotel_id')->nullable();
            $table->string('aperto_dal', 255)->default('');
            $table->string('aperto_al', 255)->default('');
            $table->tinyInteger('aperto_annuale')->default(0);
            $table->integer('sup')->default(0);
            $table->tinyInteger('a_pagamento')->default(0);
            $table->tinyInteger('in_hotel')->default(0);
            $table->integer('distanza_hotel')->default(0);
            $table->integer('eta_minima')->default(0);
            $table->tinyInteger('kit_benessere')->default(0);
            $table->tinyInteger('area_fitness')->default(0);
            $table->integer('sup_area_fitness')->default(0);
            $table->tinyInteger('obbligo_prenotazione')->default(0);
            $table->integer('uso_in_esclusiva')->default(0);
            $table->tinyInteger('piscina')->default(0);
            $table->tinyInteger('idro')->default(0);
            $table->tinyInteger('sauna_fin')->default(0);
            $table->tinyInteger('b_turco')->default(0);
            $table->tinyInteger('docce_emo')->default(0);
            $table->tinyInteger('cascate_ghiaccio')->default(0);
            $table->tinyInteger('percorso_kneipp')->default(0);
            $table->tinyInteger('aromaterapia')->default(0);
            $table->tinyInteger('cromoterapia')->default(0);
            $table->tinyInteger('massaggi')->default(0);
            $table->tinyInteger('tratt_estetici')->default(0);
            $table->tinyInteger('area_relax')->default(0);
            $table->tinyInteger('letto_marmo_riscaldato')->default(0);
            $table->tinyInteger('stanza_sale')->default(0);
            $table->text('peculiarita')->nullable();
            $table->string('suggerimento', 255)->default('');
            $table->timestamps();
            $table->index('hotel_id', 'tblinfobenessere_hotel_id_foreign');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblInfoBenessere');
    }
}
