<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblLocalitaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblLocalita', function (Blueprint $table) {
            $table->increments('id');
            $table->string('nome', 255)->default('');
            $table->string('alias', 255);
            $table->char('prov', 2)->default('');
            $table->string('cap', 5)->default('');
            $table->decimal('latitudine', 10, 6)->default(0.000000);
            $table->decimal('longitudine', 10, 6)->default(0.000000);
            $table->integer('zoom');
            $table->integer('macrolocalita_id')->default(0);
            $table->decimal('centro_lat', 10, 6)->default(0.000000);
            $table->decimal('centro_long', 10, 6)->default(0.000000);
            $table->integer('centro_raggio')->default(0);
            $table->string('centro_coordinate_note', 255);
            $table->decimal('staz_lat', 10, 6)->default(0.000000);
            $table->decimal('staz_long', 10, 6)->default(0.000000);
            $table->string('staz_coordinate_note', 255)->default('');
            $table->timestamps();
            $table->index('macrolocalita_id', 'tbllocalita_macrolocalita_id_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblLocalita');
    }
}
