<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblStatsHotelOutboundLinkTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tblStatsHotelOutboundLink', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('hotel_id');
            $table->string('ip', 20);
            $table->string('user_agent', 255);
            $table->timestamps();
            $table->index('created_at', 'tblstatshoteloutboundlink_created_at_index');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tblStatsHotelOutboundLink');
    }
}
